function onCreate()
   
    makeLuaSprite('shiftback1', 'stages/SKY/1/sky_shiftbg', -1597, -356)
    setScrollFactor('shiftback1', 1, 1)
    scaleObject('shiftback1', 3.6, 2)
    setProperty('shiftback1.alpha', 1)
    addLuaSprite('shiftback1', false)
    
    makeAnimatedLuaSprite('cloud', 'stages/SKY/1/sky_cloud', -505, -98)
    addAnimationByPrefix('cloud', 'idle', 'sky_cloud', 4, true)
    objectPlayAnimation('cloud', 'idle', true)
    setScrollFactor('cloud', 0.6, 0.5)
    scaleObject('cloud', 1.8, 1.8)
    setProperty('cloud.alpha', 0.8)
    addLuaSprite('cloud', false)
    
    makeAnimatedLuaSprite('cloudMad', 'stages/SKY/2/skyangry_cloud', -538, -136)
    addAnimationByPrefix('cloudMad', 'idle', 'messy_cloud', 4, true)
    objectPlayAnimation('cloudMad', 'idle', true)
    setScrollFactor('cloudMad', 0.6, 0.5)
    scaleObject('cloudMad', 1.8, 1.8)
    setProperty('cloudMad.alpha', 0)
    addLuaSprite('cloudMad', false)

    makeAnimatedLuaSprite('bushes', 'stages/SKY/1/sky_bush', -502, 256)
    addAnimationByPrefix('bushes', 'idle', 'sky_bush', 4, true)
    objectPlayAnimation('bushes', 'idle', true)
    setScrollFactor('bushes', 0.8, 1)
    scaleObject('bushes', 2, 2)
    setProperty('bushes.alpha', 1)
    addLuaSprite('bushes', false)
    makeAnimatedLuaSprite('bushesMad', 'stages/SKY/2/skyangry_bush', -529, 181)
    addAnimationByPrefix('bushesMad', 'idle', 'messy_bush', 4, true)
    objectPlayAnimation('bushesMad', 'idle', true)
    setScrollFactor('bushesMad', 0.8, 1)
    scaleObject('bushesMad', 2, 2)
    setProperty('bushesMad.alpha', 0)
    addLuaSprite('bushesMad', false) 
    makeAnimatedLuaSprite('tree', 'stages/SKY/1/sky_tree', 40, -331)
    addAnimationByPrefix('tree', 'idle', 'sky_tree', 4, true)
    objectPlayAnimation('tree', 'idle', true)
    setScrollFactor('tree', 1, 1)
    scaleObject('tree', 2, 2)
    setProperty('tree.alpha', 1)
    addLuaSprite('tree', false) 
    makeAnimatedLuaSprite('treeMad', 'stages/SKY/2/skyangry_tree', 15, -353)
    addAnimationByPrefix('treeMad', 'idle', 'messy_tree', 4, true)
    objectPlayAnimation('treeMad', 'idle', true)
    setScrollFactor('treeMad', 1, 1)
    scaleObject('treeMad', 2, 2)
    setProperty('treeMad.alpha', 0)
    addLuaSprite('treeMad', false)
    makeAnimatedLuaSprite('hill', 'stages/SKY/1/sky_ground', -510, 372)
    addAnimationByPrefix('hill', 'idle', 'sky_ground', 4, true)
    objectPlayAnimation('hill', 'idle', true)
    setScrollFactor('hill', 1, 1)
    scaleObject('hill', 2, 2)
    setProperty('hill.alpha', 1)
    addLuaSprite('hill', false)
    makeAnimatedLuaSprite('hillMad', 'stages/SKY/2/skyangry_ground', -545, 329)
    addAnimationByPrefix('hillMad', 'idle', 'messy_ground', 4, true)
    objectPlayAnimation('hillMad', 'idle', true)
    setScrollFactor('hillMad', 1, 1)
    scaleObject('hillMad', 2, 2)
    setProperty('hillMad.alpha', 0)
    addLuaSprite('hillMad', false)
end